export default   {
    products:[
        {
            _id:0,
            name:"DolipraneLiquiz Enfants 300 mg - 12 Sachets",
            category:"Médicament",
            image:"https://images.lasante.net/12283-85374-large.jpg",
            type: "Médicament - Allopathie",
            description: "DolipraneLiquiz 300 mg est un médicament utilisé dans le traitement de la fièvre et des douleurs telles que les maux de tête, états grippaux, courbatures, douleurs dentaires chez l'enfant de 16 à 48 kg (4 à 15 ans).",
            price: 3.32,
            Reference:  3400927897474,
            reviews:10,
            status :"En stock "
        },
        {
            _id:1,
            name:"Nicopass 1,5 mg Pastilles Menthe Fraîcheur x 96",
            category:"Médicament",
            image:"https://images.lasante.net/2073-115887-large.jpg",
            type: "Médicament - Allopathie",
            description:"Ce médicament est indiqué dans le traitement de la dépendance tabagique afin de soulager les symptômes du sevrage nicotinique chez les sujets désireux d'arrêter leur consommation de tabac.",
            price: 11.27,
            Reference: 3400936498990,
            reviews:4,
            status :"En stock "
        },
        {
            _id:2,
            name:"NurofenFlash 400 mg x 12",
            category:"Médicament",
            image:"https://images.lasante.net/134-87851-large.jpg",
            type: "Médicament - Allopathie",
            description:"Ce médicament contient un anti-inflammatoire : l'ibuprofène.Il est indiqué dans le traitement de courte durée de la fièvre.",
            price: 4.29,
            Reference: 3400936760578,
            reviews:5,
            status :"En stock "
        },
        {
            _id:3,
            name:"Dafalgan 1 g comprimés x 8",
            category:"Médicament",
            image:"https://images.lasante.net/2622-89993-large.jpg",
            type: "Médicament - Allopathie",
            description:"Ce médicament contient du paracétamol. Il est indiqué en cas de douleur et-ou fièvre telles que maux de tête, états grippaux, douleurs dentaires, courbatures, règles douloureuses.",
            price: 2.18,
            Reference:  3400936158832,
            reviews:2,
            status :"En stock "
        },
        {
            _id:4,
            name:"DLC Medical Gel hydroalcoolique 100 ml",
            category:"Pharmacie",
            image:"https://images.lasante.net/36118-117415-large.jpg",
            type: "Gel",
            description:"Sans eau et sans rinçage, DLC Medical Gel Hydroalcoolique désinfecte les mains en un seul geste! Concentration d'alcool: 70%.",
            price: 2.64,
            Reference: 3800029867250,
            rating: 5,
            reviews:17,
            status :"En stock le 07/01 !"
        },
        {
            _id:5,
            name:"Gants médicaux en latex non stériles poudrés x 100",
            category:"Pharmacie",
            image:"https://images.lasante.net/36215-117458-large.jpg",
            type: "Gants",
            description:"Gants médicaux d'examen poudrés en latex à usage unique en boîte de 100. Tailles disponibles : S,M & L.",
            price: 13.32,
            Reference: 4569871236,
            rating: 4,
            reviews:0,
            status :"En stock "
        },
        {
            _id:6,
            name:"Exacto Thermomètre Thermoflash LX26 Sans Contact Premium",
            category:"Pharmacie",
            image:"https://images.lasante.net/36121-117418-listing_new.jpg",
            type: "Thermomètre ",
            description:"Le thermoflash est un thermomètre sans contact, rapide et facile d'utilisation dans sa version Premium. ",
            price: 59.99,
            Reference: 3532678590486,
            rating: 3,
            reviews:10,
            status :"En stock le 07/31 !"
        },
        {
            _id:7,
            name:"Saforelle Recharge Soin Lavant Doux 400 ml",
            category:"Pharmacie",
            image:"https://images.lasante.net/10179-111728-large.jpg",
            type: "Soin lavant ",
            description:"Solution lavante douce à la bardan Hygiène intime, hygiène corporelle. Sensations d'inconfort, irritations. Peaux sensibles, peaux irritées. Utilisation quotidienne.",
            price: 7.40,
            Reference: 3401597168697,
            rating:5,
            reviews:0,
            status :"En stock "
        },
        {
            _id:8,
            name:"Synergia D-Stress x 80",
            category:"Bien-être & Nutrition",
            image:"https://images.lasante.net/1865-111690-large.jpg",
            type: "comprimés",
            description:"On ne présente plus D-Stress, le best seller de Synergia ! Riche en vitamines et minéraux, il réduit la fatigue, augmente la résistance au stress, et aide à retrouver des capacités intellectuelles optimales !",
            price: 10.89,
            Reference: 3401576419437,
            rating:3,
            reviews:15,
            status :"En stock le 06/09 !"
        },
        {
            _id:9,
            name:"PiLeJe Lactibiane Référence Gélules x 30",
            category:"Bien-être & Nutrition",
            image:"https://images.lasante.net/2561-104561-large.jpg",
            type: "Gélules",
            description:"Complément alimentaire à base de 4 souches microbiotiques dosées à 10 milliards par gélule ou par sachet de 2.5 g.",
            price: 19.90,
            Reference: 3401560504828,
            rating:5,
            reviews:4,
            status :"En stock"
        },
        {
            _id:10,
            name:"Novanuit Triple Action x 30",
            category:"Bien-être & Nutrition",
            image:"https://images.lasante.net/32563-113946-large.jpg",
            type: "Comprimés",
            description:"Novanuit est un complément alimentaire 3 en 1 qui vous offre un sommeil de meilleur qualité en agissant sur l'endormissement, les insomnies et le sommeil réparateur. Résultats visibles dès 15 jours ! Sans risque de dépendance.",
            price: 8.97,
            Reference: 4,
            rating:0,
            reviews:0,
            status :"En stock le 07/28!"
        },
        {
            _id:11,
            name:"Nutrof Total x 180",
            category:"Bien-être & Nutrition",
            image:"https://images.lasante.net/3623-90864-large.jpg",
            type: "Gélules ",
            description:"Complément alimentaire à visée occulaire Vitamines et Oligo-éléments anti-oxydant Acides gras essentiels Lutéine et Zéaxanthin,Extrait de Vitis Vinifera",
            price: 53,
            Reference: 3662042003547,
            rating:0,
            reviews:0,
            status :"En stock le 08/09 !"
        },
        {
            _id:12,
            name:"Gilbert Bactidose Gel Hydroalcoolique Sans Parfum 100 ml",
            category:"Hygiène & Premiers soins",
            image:"https://images.lasante.net/35962-118033-large.jpg",
            type: "Gel 100 ml",
            description:"Ce gel hydroalcoolique lave les mains sans eau ni savon. Il élimine efficacement les bactéries et protège contre les virus. Sans parfum.",
            price: 2.99,
            Reference: 3518646213380,
            rating:0,
            reviews:0,
            status :"En stock "
        },
        {
            _id:13,
            name:"Nuxe Bio Masque Détoxifiant Éclat 50 ml",
            category:"Beauté & Soins",
            image:"https://images.lasante.net/35227-117448-large.jpg",
            type: "Masque 50 ml",
            description:"Le Masque Détoxifiant Eclat de Nuxe BIO est un soin visage qui détoxifie la peau en cas de teint terne.",
            price: 22.9,
            Reference: 3264680023910,
            rating:0,
            reviews:0,
            status :"En stock le 07/09 !"
        },
        {
            _id:14,
            name:"Nuxe Bio Soin Yeux Energisant Anti-poches et Anti-cernes 15 ml",
            category:"Beauté & Soins",
            image:"https://images.lasante.net/35223-117444-listing_new.jpg",
            type: "Crème 15 ml",
            description:"Ce soin bio protège, hydrate et lisse les signes de fatigue du contour de l'œil. Adapté à toutes les peaux.",
            price: 26.99,
            Reference: 3264680023248,
            rating:0,
            reviews:0,
            status :"En stock"
        },
        {
            _id:15,
            name:"Nuxe Bio Eau Micellaire Démaquillante 200 ml",
            category:"Beauté & Soins",
            image:"https://images.lasante.net/35224-117445-listing_new.jpg",
            type: "Solution Micellaire 200 ml",
            description:"Eau micellaire bio sans rinçage qui purifie, démaquille et nettoie votre visage et vos yeux. Convient à tous types de peaux, y compris les plus sensibles.",
            price: 14.99,
            Reference: 3264680023033,
            rating:5,
            reviews:5,
            status :"En stock"
        },
        {
            _id:16,
            name:"Nuxe Bio Sérum Essentiel Antioxydant 30 ml",
            category:"Beauté & Soins",
            image:"https://images.lasante.net/35229-117450-large.jpg",
            type: "Sérum 30 ml",
            description:"Cet anti-oxydant longue durée contribue à préserver les signes de jeunesse de la peau. Contient 99 % d'ingrédients d'origine naturelle.",
            price: 35.99,
            Reference: 3264680023101,
            rating:5,
            reviews:0,
            status :"En stock"
        },
        {
            _id:17,
            name:"Audispray Adulte sans gaz 50 ml",
            category:"Hygiène & Premiers soins",
            image:"https://images.lasante.net/1737-106412-large.jpg",
            type: "Spray 50 ml",
            description:"Solution auriculaire hypertonique d'eau de mer.Hygiène auriculaire. Bouchons de cérumen. Adulte.",
            price: 6.89,
            Reference: 7640107850141,
            rating:5,
            reviews:1,
            status :"En stock"
        },
        {
            _id:18,
            name:"Audispray Junior Sans Gaz 25 ml",
            category:"Hygiène & Premiers soins",
            image:"https://images.lasante.net/1752-106415-large.jpg",
            type: "Spray 25 ml",
            description:"Solution auriculaire d'eau de mer.Hygiène auriculaire. Enfant à partir de 3 ans.",
            price: 5.98,
            Reference:  7640107850622,
            rating:5,
            reviews:1,
            status :"En stock"
        },
        {
            _id:19,
            name:"Etiaxil Déodorant Anti-transpirant 48h Aérosol 150 ml",
            category:"Hygiène & Premiers soins",
            image:"https://images.lasante.net/17579-107399-large.jpg",
            type: "Spray 150 ml ",
            description:"Déodorant qui agit efficacement toute la journée. Fraîcheur et régulation. Utilisation quotidienne. Aérosol sans alcool.",
            price: 6.34,
            Reference: 3401360114890,
            rating:0,
            reviews:0,
            status :"En stock"

        },
        {
            _id:20,
            name:"Audibaby Hygiène de l'Oreille x 10",
            category:"Hygiène & Premiers soins",
            image:"https://images.lasante.net/33149-114000-large.jpg",
            type: "Unidoses x 10",
            description:"Audibaby est une solution d’eau de mer stérile en unidose qui nettoie en douceur les oreilles de bébé.",
            price: 5.88,
            Reference: 7640107850813,
            rating:0,
            reviews:0,
            status :"En stock"
        },
        {
            _id:21,
            name:"Gilbert Physiodose Sérum Physiologique Stérile 2 x 40 x 5 ml",
            category:"Bébé & Maman",
            image:"https://images.lasante.net/13416-110569-large.jpg",
            type: "Sérum physiologique 2 x 40 ml",
            description:"Physiodose sérum physiologique est idéal pour l'hygiène nasale, oculaire et auriculaire chez les nourrissons, les enfants et les adultes. Format économique avec ce lot de 2 x 40 unidoses de 5 ml.",
            price: 4.08,
            Reference: 3663702101658,
            rating:5,
            reviews:1,
            status :"En stock"
        },
        {
            _id:22,
            name:"Mustela Gel Lavant Doux 500 ml",
            category:"Bébé & Maman",
            image:"https://images.lasante.net/23457-111692-large.jpg",
            type: "Gel moussant 500 ml",
            description:"Spécifiquement formulé pour le bain de bébé, le gel lavant doux pour cheveux et corps Mustela nettoie en douceur sans dessécher la peau fragile de votre enfant.",
            price: 7.32,
            Reference: 3504105028374,
            rating:5,
            reviews:7,
            status :"En stock"
        },
        {
            _id:23,
            name:"Oddibil x 40",
            category:"Bio Médecines naturelles",
            image:"https://images.lasante.net/93-117454-large.jpg",
            description:"Traditionnellement utilisé pour faciliter les fonctions d'élimination de l'organisme.",
            type: "Comprimés enrobés x 40",
            price: 3.55,
            Reference: 3400930747438,
            rating:3,
            reviews:4,
            status :"En stock"
        },
        {
            _id:24,
            name:"Contour Next Bandelettes pour Lecteur de Glycémie x 50",
            category:"Matériel Médical",
            image:"https://images.lasante.net/26095-110370-large.jpg",
            type: "Bandelettes x 50",
            description:"Ces bandelettes réactives sont conçues pour effectuer les mesures de la glycémie pour les personnes diabétiques qui procèdent à une surveillance glycémique.",
            price: 18.75,
            Reference: 3401051049166,
            rating:3,
            reviews:0,
            status :"En stock"

        }
    ]
}